### ISSUE TITLE
Trying to add Gmail as App/Integration returns "Cannot read property 'data' of undefined"

### ISSUE THREAD

**Issue by ned-kelly** [erxes/erxes#1714]
Hi guys,

Just trying to add Gmail as an integration here using the latest 0.12.x (was previously on 0.10.x and had the same issue) and I'm getting an error from your `erxes-integrations` service...

```
2020-03-04T03:30:46.709Z erxes-integrations:gmail Creating gmail integration for
2020-03-04T03:30:46.714Z erxes-integrations:gmail Watch push notification for this  user
2020-03-04T03:30:46.714Z erxes-integrations:gmail Google OAuthClient request to watch push notification for the given user mailbox
2020-03-04T03:30:47.861Z erxes-integrations:gmail Google OAuthClient request to watch push notification failed Error: Invalid topic name format. Should follow 'projects/my-project-id/topics/my-topic-id'
2020-03-04T03:30:47.862Z erxes-integrations:gmail Error Google: Could not subscribe user  to topic
TypeError: Cannot read property 'data' of undefined
    at /erxes-integrations/dist/gmail/controller.js:100:46
    at step (/erxes-integrations/dist/gmail/controller.js:44:23)
    at Object.next (/erxes-integrations/dist/gmail/controller.js:25:53)
    at fulfilled (/erxes-integrations/dist/gmail/controller.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-03-04T03:30:47.864Z erxes-integrations:gmail Successfully created the gmail integration
2020-03-04T03:30:47.864Z erxes-integrations:gmail Responding /gmail/create-integration request to undefined with success
(node:1) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/erxes-integrations/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/erxes-integrations/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/erxes-integrations/node_modules/express/lib/response.js:267:15)
    at /erxes-integrations/dist/gmail/controller.js:114:51
    at step (/erxes-integrations/dist/gmail/controller.js:44:23)
    at Object.next (/erxes-integrations/dist/gmail/controller.js:25:53)
    at fulfilled (/erxes-integrations/dist/gmail/controller.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Any help would be greatly appreciated!

**Comment by munkhorgil** [comment]
Hey, @ned-kelly it looks like you did not provide GOOGLE_GMAIL_TOPIC in env, can I see your env

**Comment by ned-kelly** [comment]
Nope it's all setup ok...

```
    environment:
      PORT: "3400"
      NODE_ENV: production
      DEBUG: "erxes-integrations:*"
      # public urls
      DOMAIN: https://integrations.xxxxxxx
      MAIN_APP_DOMAIN: https://engagement.xxxxxx
      MAIN_API_DOMAIN: https://api.xxxxx
      # non public urls
      # MongoDB
      MONGO_URL: mongodb://mongo/erxes_integrations
      # RabbitMQ
      RABBITMQ_HOST: "amqp://guest:guest@rabbitmq:5672/erxes"
      # Facebook
      FACEBOOK_APP_ID: ""
      FACEBOOK_APP_SECRET: ""
      FACEBOOK_VERIFY_TOKEN: ""

      # Gmail / GCE
      GOOGLE_PROJECT_ID: "xxxxx"
      GOOGLE_GMAIL_TOPIC: "projects/xxxxx/topics/erxes"
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/keys/xxxxxx.json"
      GOOGLE_GMAIL_SUBSCRIPTION_NAME: "projects/xxxxx/subscriptions/erxes-subscription"
      GOOGLE_CLIENT_ID: "xxxxxx.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "xxxxx"
      GMAIL_REDIRECT_URL: "<MAIN_APP_DOMAIN>/service/oauth/gmail_callback"
```

**Comment by munkhorgil** [comment]
Following env must be as follows:
```
GOOGLE_GMAIL_TOPIC: "erxes"
GOOGLE_GMAIL_SUBSCRIPTION_NAME: "erxes-subscription"
```

**Comment by gfigueroaalmera** [comment]
What is GOOGLE_GMAIL_TOPIC and GOOGLE_GMAIL_SUBSCRIPTION_NAME??

**Comment by munkhorgil** [comment]
@gfigueroaalmera It could be any string such we usually go as gmail_topic, gmail_subscription

**Comment by batamar** [comment]
@gfigueroaalmera Too old. Feel free to open
