### ISSUE TITLE
Unable to successfully complete docker installation with version 0.20.1

### ISSUE THREAD

**Issue by tfoxcroft** [erxes/erxes#2849]
**Describe the bug**
Good day, Im busy trying to install erxes using the docker installlation steps as outlined here: https://www.erxes.org/installation/docker/ .

All containers appear to start successfully and I am able to login to the system, however I am not sure every is correctly setup because when I navigate to the System Status page, the page does not load. Also, when I change the upload type from Amazon Web Service to Local, I get an error when trying to import data "socket hang up" which leads me to believe some parts of the system are not correct.

**To Reproduce**
1. I already had docker, and docker-compose installed
2. Create a folder to hold the docker-compose.yml file and data
3. Copied the docker-compose.yml exactly as on the instructions, only change made was to update 0.17.6 to 0.20.1
4. Create required folders: `mkdir elasticsearch-data && chown 1000:1000 elasticsearch-data`
5. Start containers: `docker-compose up -d`
6. Initialise project: `docker exec -it erxes-api yarn initProject` and noted password
7. Ran final scipt `docker exec -it erxes-api yarn loadPermission` . Note the installation instuctions reference a script called loadPermissionData, however after searching I found I needed to change it to loadPermission, which appeared to work
8. Log into system
9. Navigate to system status page: http://localhost:3000/settings/status , which hangs
10. Navigate to settings page: http://localhost:3000/settings/general
11. Change upload type from Amazon Web Service to Local
12. Navigate to companies import: http://localhost:3000/settings/importHistories?type=company
11. Importing file results in "socket hang up" error

**Expected behavior**
I would expect the system status page to load so that I can ensure the various system components all installed successfully.

**Screenshots**
![status-page](https://user-images.githubusercontent.com/716894/123113998-44f70680-d43f-11eb-929e-2a2e583eb4ce.png)
![socket-hang-up](https://user-images.githubusercontent.com/716894/123114013-47596080-d43f-11eb-81e9-0d5e6e65f668.png)

docker logs of the erxes-workers container during socket hangup
![socket-hang-up-logs](https://user-images.githubusercontent.com/716894/123115489-6efcf880-d440-11eb-9e14-89a806389ac0.png)

**Context (please include the related information if applicable):**
 - OS: Ubuntu 21.04
 - Browser: Google Chrome Version 91.0.4472.106 (Official Build) (64-bit)
 - erxes version: 0.20.1
 - installation type: docker

**Additional context**
I tried the same on the 0.17.6 version used in the installation instructions. The status page loaded fine there, but was still not able to upload a file, I received the same "socket hang up" error. I have also repeated the same steps on another evironment (also an ubuntu server), with the same results.

Thanks,

**Comment by tfoxcroft** [comment]
Text version of the docker logs of the erxes-workers container during socket hangup error:

```
2021-06-23T14:19:27.028Z erxes-workers: Workers server is now running on 3700
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/erxes-api/dist/private/uploads/0.5792082109510319company-import-template-1.csv'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:136:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/erxes-api/dist/private/uploads/0.5792082109510319company-import-template-1.csv'
}
```

**Comment by KhongorzulD** [comment]
Hello @tfoxcroft, I am apologizing for the late response. However, do you still have this issue or did you already solve it?. I would very much appreciate if you give me a response. Thank you
