### ISSUE TITLE
Error: Integrations api is not running

### ISSUE THREAD

**Issue by Jarrodsz** [erxes/erxes#3104]
**Describe the bug**
Error: Integrations api is not running

**To Reproduce**
Docker deployment on localhost

**Expected behavior**
Be able to add an integration like map

**Context (please include the related information if applicable):**
 - OSX latest versions of docker + containers
 

```2021-11-09T17:37:18.722Z erxes-integrations:init Integrations server is running on port 3400

(node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

2021-11-09T17:37:18.800Z erxes-integrations:db Disconnected from the database: mongodb://mongo/erxes

2021-11-09T17:37:18.804Z erxes-integrations:db Database connection error: mongodb://mongo/erxes MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.24.0.15:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {

  name: 'MongoNetworkError',

  errorLabels: [Array],

  [Symbol(mongoErrorContextSymbol)]: {}

}]

(node:1) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect ECONNREFUSED 172.24.0.15:27017

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {

  name: 'MongoNetworkError',

  errorLabels: [Array],

  [Symbol(mongoErrorContextSymbol)]: {}

}]

    at Pool.<anonymous> (/erxes-integrations/node_modules/mongodb/lib/core/topologies/server.js:431:11)

    at Pool.emit (events.js:314:20)

    at /erxes-integrations/node_modules/mongodb/lib/core/connection/pool.js:580:14

    at /erxes-integrations/node_modules/mongodb/lib/core/connection/connect.js:25:9

    at callback (/erxes-integrations/node_modules/mongodb/lib/core/connection/connect.js:261:5)

    at Socket.<anonymous> (/erxes-integrations/node_modules/mongodb/lib/core/connection/connect.js:286:7)

    at Object.onceWrapper (events.js:421:26)

    at Socket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Search...
Stick to bottom```

**Comment by Jarrodsz** [comment]
Any fixes updates on the docker deployment?
