### ISSUE TITLE
CE Quick Start: Cannot find module 'colors'

### ISSUE THREAD

**Issue by coderdude72** [erxes/erxes#3211]
When using the CE Quick Starton Ubuntu 18, I am getting an error with colors.

I use the command from the docs: bash -c "$(wget -O - https://raw.githubusercontent.com/erxes/erxes/develop/scripts/install/ubuntu18.sh)"

Eventually, after it installs pm2, I get this error:

````
$ erxes start
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack:
- /home/erxes/erxes.io/erxes/node_modules/erxes/commands/utils.js
- /home/erxes/erxes.io/erxes/node_modules/erxes/commands/start.js
- /home/erxes/erxes.io/erxes/node_modules/erxes/bin/erxes.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/erxes/erxes.io/erxes/node_modules/erxes/commands/utils.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/erxes/erxes.io/erxes/node_modules/erxes/commands/utils.js',
    '/home/erxes/erxes.io/erxes/node_modules/erxes/commands/start.js',
    '/home/erxes/erxes.io/erxes/node_modules/erxes/bin/erxes.js'
  ]
}
error Command failed with exit code 1.
````

**Comment by bnomio19** [comment]
Hello @coderdude72, @Enkhtuvshin0513 will help you to solve this prob. You may have missed some commands In this issue.
