### ISSUE TITLE
Cannot install on M1 macbook pro

### ISSUE THREAD

**Issue by radaniba** [erxes/erxes#3904]
Hi everyone,
I followed the documentation for local installation but I am running through issues as the server doesn't start

```
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ core         │ default     │ N/A     │ fork    │ 0        │ 0      │ 135  │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 4   │ coreui       │ default     │ N/A     │ fork    │ 0        │ 0      │ 105  │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 2   │ dashboard    │ default     │ N/A     │ fork    │ 0        │ 0      │ 105  │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 3   │ gateway      │ default     │ N/A     │ fork    │ 0        │ 0      │ 105  │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 1   │ logs-api     │ default     │ N/A     │ fork    │ 0        │ 0      │ 136  │ errored   │ 0%       │ 0b       │ root     │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```

I am not sure what went wrong with the setup

I am using node v19.2.0

**Comment by mendorshikh** [comment]
@Myagmarsuren-a Please followup here.

**Comment by radaniba** [comment]
I also downgraded to node v14 and had the same result as well.

**Comment by mendorshikh** [comment]
@radaniba You followed following docs right: https://docs.erxes.io/docs/category/setup--deployment

**Comment by radaniba** [comment]
@mendorshikh yes correct, the local installation part I confirm

**Comment by Myagmarsuren-a** [comment]
@radaniba Hi, can you show me some of service's error log by pm2 logs <ID of service>.

**Comment by radaniba** [comment]
Hi @Myagmarsuren-a 
Certainly

Here is the log trail

```
pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/Users/mohamedaniba/.pm2/pm2.log last 15 lines:
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] online
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] starting in -fork mode-
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] online
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] starting in -fork mode-
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] online
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] starting in -fork mode-
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] online
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] starting in -fork mode-
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] online
PM2        | 2022-12-07T13:04:43: PM2 log: App [coreui:4] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-07T13:04:43: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"

/Users/mohamedaniba/.pm2/logs/core-out.log last 15 lines:
/Users/mohamedaniba/.pm2/logs/logs-api-out.log last 15 lines:
/Users/mohamedaniba/.pm2/logs/dashboard-out.log last 15 lines:
/Users/mohamedaniba/.pm2/logs/gateway-out.log last 15 lines:
/Users/mohamedaniba/.pm2/logs/coreui-out.log last 15 lines:
/Users/mohamedaniba/.pm2/logs/core-error.log last 15 lines:
0|core     | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
0|core     | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
0|core     |                        ^^^^
0|core     |
0|core     | SyntaxError: Unexpected identifier
0|core     |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
0|core     |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
0|core     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|core     |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|core     |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
0|core     |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|core     |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|core     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|core     |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|core     |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

/Users/mohamedaniba/.pm2/logs/logs-api-error.log last 15 lines:
1|logs-api | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
1|logs-api | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
1|logs-api |                        ^^^^
1|logs-api |
1|logs-api | SyntaxError: Unexpected identifier
1|logs-api |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
1|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
1|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|logs-api |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
1|logs-api |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
1|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|logs-api |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

/Users/mohamedaniba/.pm2/logs/dashboard-error.log last 15 lines:
2|dashboar | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
2|dashboar | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
2|dashboar |                        ^^^^
2|dashboar |
2|dashboar | SyntaxError: Unexpected identifier
2|dashboar |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2|dashboar |     at Module.load (internal/modules/cjs/loader.js:950:32)
2|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2|dashboar |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2|dashboar |     at Module.load (internal/modules/cjs/loader.js:950:32)
2|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

/Users/mohamedaniba/.pm2/logs/gateway-error.log last 15 lines:
3|gateway  | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
3|gateway  | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
3|gateway  |                        ^^^^
3|gateway  |
3|gateway  | SyntaxError: Unexpected identifier
3|gateway  |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
3|gateway  |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
3|gateway  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
3|gateway  |     at Module.load (internal/modules/cjs/loader.js:950:32)
3|gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
3|gateway  |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
3|gateway  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
3|gateway  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
3|gateway  |     at Module.load (internal/modules/cjs/loader.js:950:32)
3|gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

/Users/mohamedaniba/.pm2/logs/coreui-error.log last 15 lines:
4|coreui   | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
4|coreui   | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
4|coreui   |                        ^^^^
4|coreui   |
4|coreui   | SyntaxError: Unexpected identifier
4|coreui   |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
4|coreui   |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
4|coreui   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
4|coreui   |     at Module.load (internal/modules/cjs/loader.js:950:32)
4|coreui   |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
4|coreui   |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
4|coreui   |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
4|coreui   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
4|coreui   |     at Module.load (internal/modules/cjs/loader.js:950:32)
4|coreui   |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

```

**Comment by Myagmarsuren-a** [comment]
@radaniba it looks like your homebrew messed up yarn install can you try to reinstall your yarn. I have same yarn version but it works fine for me.

**Comment by radaniba** [comment]
Thank you @Myagmarsuren-a 
I reinstalled Yarn not through homebrew though and it worked
the UI is showing "hang in there we will be right back with you" but it is hanging for some time, normal ?
Rad

**Comment by Myagmarsuren-a** [comment]
@radaniba Can you show me some logs if it hangs mostly it did not connected to backend.

**Comment by radaniba** [comment]
Hi @Myagmarsuren-a  certainy

Please note : This behaviour also occurs on your own website when users hit the demo button !

```

➜  erxes git:(dev) ✗ pm2 logs                
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/Users/mohamedaniba/.pm2/pm2.log last 15 lines:
PM2        | 2022-12-09T12:14:06: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2022-12-09T12:14:06: PM2 log: App [dashboard:2] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-09T12:14:06: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2022-12-09T12:14:06: PM2 log: App [logs-api:1] exited with code [1] via signal [SIGINT]
PM2        | 2022-12-09T12:14:06: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2022-12-09T12:17:26: PM2 log: App [core:0] starting in -fork mode-
PM2        | 2022-12-09T12:17:26: PM2 log: App [core:0] online
PM2        | 2022-12-09T12:17:57: PM2 log: App [logs-api:1] starting in -fork mode-
PM2        | 2022-12-09T12:17:57: PM2 log: App [logs-api:1] online
PM2        | 2022-12-09T12:18:07: PM2 log: App [dashboard:2] starting in -fork mode-
PM2        | 2022-12-09T12:18:07: PM2 log: App [dashboard:2] online
PM2        | 2022-12-09T12:18:17: PM2 log: App [gateway:3] starting in -fork mode-
PM2        | 2022-12-09T12:18:17: PM2 log: App [gateway:3] online
PM2        | 2022-12-09T12:18:27: PM2 log: App [coreui:4] starting in -fork mode-
PM2        | 2022-12-09T12:18:27: PM2 log: App [coreui:4] online

/Users/mohamedaniba/.pm2/logs/dashboard-error.log last 15 lines:
2|dashboar | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
2|dashboar | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
2|dashboar |                        ^^^^
2|dashboar | 
2|dashboar | SyntaxError: Unexpected identifier
2|dashboar |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2|dashboar |     at Module.load (internal/modules/cjs/loader.js:950:32)
2|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2|dashboar |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2|dashboar |     at Module.load (internal/modules/cjs/loader.js:950:32)
2|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

/Users/mohamedaniba/.pm2/logs/core-error.log last 15 lines:
0|core     | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|core     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
0|core     | (node:14727) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
0|core     |     at Socket.<anonymous> (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/ioredis/built/redis/event_handler.js:177:37)
0|core     |     at Object.onceWrapper (events.js:520:26)
0|core     |     at Socket.emit (events.js:400:28)
0|core     |     at Socket.emit (domain.js:475:12)
0|core     |     at TCP.<anonymous> (net.js:686:12)
0|core     | (node:14727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|core     | (node:14727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|core     | node_redis: Warning: Redis server does not require a password, but a password was supplied.
0|core     | node_redis: Warning: Redis server does not require a password, but a password was supplied.
0|core     | node_redis: Warning: Redis server does not require a password, but a password was supplied.
0|core     | node_redis: Warning: Redis server does not require a password, but a password was supplied.
0|core     | node_redis: Warning: Redis server does not require a password, but a password was supplied.

/Users/mohamedaniba/.pm2/logs/logs-api-out.log last 15 lines:
1|logs-api | yarn run v1.22.19
1|logs-api | $ cd .erxes && yarn dev
1|logs-api | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

/Users/mohamedaniba/.pm2/logs/logs-api-error.log last 15 lines:
1|logs-api | 
1|logs-api | SyntaxError: Unexpected identifier
1|logs-api |     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
1|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1049:27)
1|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|logs-api |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
1|logs-api |     at Object.<anonymous> (/opt/homebrew/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
1|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|logs-api |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
1|logs-api | warning package.json: No license field
1|logs-api | /bin/sh: line 0: cd: .erxes: No such file or directory
1|logs-api | error Command failed with exit code 1.

/Users/mohamedaniba/.pm2/logs/gateway-error.log last 15 lines:
3|gateway  | Polling running services is dangerous and not recommended in production. Polling should only be used against a registry. If you are polling running services, use with caution.
3|gateway  | Error: Tried to load services from remote endpoints but none provided
3|gateway  |     at getServiceDefinitionsFromRemoteEndpoint (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@apollo/gateway/src/loadServicesFromRemoteEndpoint.ts:25:11)
3|gateway  |     at ApolloGateway.loadServiceDefinitions (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@apollo/gateway/src/index.ts:961:53)
3|gateway  |     at ApolloGateway.updateSchema (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@apollo/gateway/src/index.ts:484:31)
3|gateway  |     at ApolloGateway.loadDynamic (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@apollo/gateway/src/index.ts:464:18)
3|gateway  |     at ApolloGateway.load (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@apollo/gateway/src/index.ts:423:20)
3|gateway  |     at SchemaManager.start (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/apollo-server-core/src/utils/schemaManager.ts:111:59)
3|gateway  |     at ApolloServer._start (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/apollo-server-core/src/ApolloServer.ts:359:44)
3|gateway  |     at ApolloServer.start (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/apollo-server-core/src/ApolloServer.ts:340:23)
3|gateway  |     at /Users/mohamedaniba/Documents/Dev/erxes/erxes/packages/gateway/src/index.ts:168:24
3|gateway  |     at Generator.next (<anonymous>)
3|gateway  |     at fulfilled (/Users/mohamedaniba/Documents/Dev/erxes/erxes/packages/gateway/src/index.ts:5:58)
3|gateway  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
3|gateway  | Gateway might have started before enabled services are ready.

/Users/mohamedaniba/.pm2/logs/gateway-out.log last 15 lines:
3|gateway  | successfully updated plugin-tags-api
3|gateway  | successfully updated plugin-webbuilder-api
3|gateway  | successfully updated plugin-webhooks-api
3|gateway  | ╔══════════════════════════════════════════════╗
3|gateway  | ║                                              ║
3|gateway  | ║   Erxes collects anonymous usage analytics   ║
3|gateway  | ║   to help improve Erxes for all users.       ║
3|gateway  | ║                                              ║
3|gateway  | ║                                              ║
3|gateway  | ╚══════════════════════════════════════════════╝
3|gateway  | Clearing enabled services cache ........
3|gateway  | [HPM] Proxy created: /  -> http://localhost:3300
3|gateway  | core has no address value
3|gateway  | logs has no address value
3|gateway  | [nodemon] app crashed - waiting for file changes before starting...

/Users/mohamedaniba/.pm2/logs/core-out.log last 15 lines:
0|core     | [nodemon] watching path(s): *.*
0|core     | [nodemon] watching extensions: ts,json
0|core     | [nodemon] starting `ts-node src/index.ts`
0|core     | Enabling inline tracing for this federated service. To disable, use ApolloServerPluginInlineTraceDisabled.
0|core     | Failed to connect to rabbitmq server Error: connect ECONNREFUSED 127.0.0.1:5672
0|core     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
0|core     |   errno: -61,
0|core     |   code: 'ECONNREFUSED',
0|core     |   syscall: 'connect',
0|core     |   address: '127.0.0.1',
0|core     |   port: 5672
0|core     | }
0|core     | Scheduling reconnect to rabbitmq in 60s
0|core     | Now attempting reconnect to rabbitmq ...
0|core     | Connected to rabbitmq server amqp://localhost?heartbeat=60

/Users/mohamedaniba/.pm2/logs/coreui-error.log last 15 lines:
4|coreui   | 
4|coreui   | 
4|coreui   |   Replace Autoprefixer browsers option to Browserslist config.
4|coreui   |   Use browserslist key in package.json or .browserslistrc file.
4|coreui   | 
4|coreui   |   Using browsers option can cause errors. Browserslist config can
4|coreui   |   be used for Babel, Autoprefixer, postcss-normalize and other tools.
4|coreui   | 
4|coreui   |   If you really need to use option, rename it to overrideBrowserslist.
4|coreui   | 
4|coreui   |   Learn more at:
4|coreui   |   https://github.com/browserslist/browserslist#readme
4|coreui   |   https://twitter.com/browserslist
4|coreui   | 
4|coreui   | 

/Users/mohamedaniba/.pm2/logs/coreui-out.log last 15 lines:
4|coreui   | asset index.html 19.4 KiB [emitted]
4|coreui   | runtime modules 179 KiB 41 modules
4|coreui   | orphan modules 27.2 KiB (javascript) 42 bytes (consume-shared) [orphan] 11 modules
4|coreui   | modules by path ../../node_modules/ 9.64 MiB (javascript) 944 KiB (asset)
4|coreui   |   javascript modules 9.64 MiB 1527 modules
4|coreui   |   asset modules 210 bytes (javascript) 944 KiB (asset) 5 modules
4|coreui   | modules by path ../erxes-ui/ 1.07 MiB
4|coreui   |   modules by path ../erxes-ui/src/ 746 KiB 165 modules
4|coreui   |   modules by path ../erxes-ui/node_modules/ 354 KiB 109 modules
4|coreui   | modules by path ./ 5.8 MiB 264 modules
4|coreui   | consume-shared-module modules 2.01 KiB 49 modules
4|coreui   | provide-module modules 1.56 KiB 38 modules
4|coreui   | modules by path ../ui-settings/src/ 69.5 KiB 18 modules
4|coreui   | container entry 42 bytes [built] [code generated]
4|coreui   | webpack 5.68.0 compiled successfully in 9910 ms

/Users/mohamedaniba/.pm2/logs/dashboard-out.log last 15 lines:
2|dashboar | {
2|dashboar |   "securityContext": {}
2|dashboar | } 
2|dashboar | Error: Unsupported db type: undefined
2|dashboar |     at Object.driverDependencies (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:24:9)
2|dashboar |     at Object.lookupDriverClass (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:36:5)
2|dashboar |     at Object.dialectFactory (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:450:9)
2|dashboar |     at CompilerApi.dialectClass (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/server.ts:461:26)
2|dashboar |     at CompilerApi.getDialectClass (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:91:38)
2|dashboar |     at CompilerApi.createQueryByDataSource (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:159:53)
2|dashboar |     at async RefreshScheduler.refreshCubesRefreshKey (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:249:32)
2|dashboar |     at async Promise.all (index 0)
2|dashboar |     at async RefreshScheduler.runScheduledRefresh (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:199:9)
2|dashboar |     at async Promise.all (index 0)
2|dashboar |     at async Timeout._onTimeout (/Users/mohamedaniba/Documents/Dev/erxes/erxes/node_modules/@cubejs-backend/shared/src/promises.ts:139:9)



```


and pm2 list 

```
erxes git:(dev) ✗ pm2 list
┌─────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ core         │ default     │ N/A     │ fork    │ 14705    │ 49m    │ 30   │ online    │ 0%       │ 34.8mb   │ root     │ disabled │
│ 4   │ coreui       │ default     │ N/A     │ fork    │ 15024    │ 48m    │ 30   │ online    │ 0%       │ 38.3mb   │ root     │ disabled │
│ 2   │ dashboard    │ default     │ N/A     │ fork    │ 14857    │ 49m    │ 30   │ online    │ 0%       │ 38.1mb   │ root     │ disabled │
│ 3   │ gateway      │ default     │ N/A     │ fork    │ 14908    │ 48m    │ 30   │ online    │ 0%       │ 36.2mb   │ root     │ disabled │
│ 1   │ logs-api     │ default     │ N/A     │ fork    │ 14828    │ 49m    │ 30   │ online    │ 0%       │ 36.8mb   │ root     │ disabled │
└─────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. App bin . differs. Type 'pm2 save' to synchronize.

```

**Comment by Myagmarsuren-a** [comment]
@radaniba seems like you need to restart gateway. Because gateway service must start after all services. Also your rabbitmq and redis did not started.

**Comment by radaniba** [comment]
FANTASTIC ! Yes that was the issue indeed,
thanks for your patience @Myagmarsuren-a  it works just fine now

**Comment by jacobburrell** [comment]
Having this issue,

I tried restarting Gateway to ensure it is the last service that starts.
`pm2 restart gateway`

Docker ps and their corresponding directories for rabbitmq and redis look to be working too. 

I'm following [this guide](https://docs.erxes.io/docs/deployment/installation/installation-mac)

@radaniba Do you recall the steps that worked for you?

**Comment by ImpossibleReality** [comment]
I am also having this issue. @jacobburrell Have you found a solution to it?

**Comment by radaniba** [comment]
@jacobburrell and @ImpossibleReality sorry guys I don't recall how this was fixed I will get back to my notes and let you guys know but I moved from exploring erxces unfortunatley

**Comment by vinyll** [comment]
I solved uninstalling yarn from Homebrew and installing via npm:
```
brew uninstall yarn   
npm install --global yarn
```
