### ISSUE TITLE
Gateway constantly restarting

### ISSUE THREAD

**Issue by McLeanAdam** [erxes/erxes#4533]
**Describe the bug**
After install the main gateway container constantly restarts.

**To Reproduce**
Follow the step from the installation guide 

**Expected behavior**
All containers should operate as expected

**Screenshots/Logs**
Log output from gateway container before been destroyed
```
Clearing enabled services cache ........
(node:1) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:1) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Plugin products joined service discovery.
Plugin core joined service discovery.
Plugin workers joined service discovery.
Plugin forms joined service discovery.
Plugin integrations joined service discovery.
Plugin logs joined service discovery.
Plugin tags joined service discovery.
Plugin contacts joined service discovery.
Plugin notifications joined service discovery.
Plugin internalnotes joined service discovery.
Plugin products's graphql endpoint http://plugin-products-api/graphql is up.
Plugin core's graphql endpoint http://plugin-core-api/graphql is up.
Plugin workers's graphql endpoint http://plugin-workers-api/graphql is up.
Plugin integrations's graphql endpoint http://plugin-integrations-api/graphql is up.
Plugin logs's graphql endpoint http://plugin-logs-api/graphql is up.
Plugin tags's graphql endpoint http://plugin-tags-api/graphql is up.
Plugin notifications's graphql endpoint http://plugin-notifications-api/graphql is up.
Plugin forms's graphql endpoint http://plugin-forms-api/graphql is up.
Plugin contacts's graphql endpoint http://plugin-contacts-api/graphql is up.
Plugin internalnotes's graphql endpoint http://plugin-internalnotes-api/graphql is up.
(node:1) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/erxes-gateway/dist/gateway/src/apollo-router/temp/supergraph.yaml'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at createSupergraphConfig (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:40:12)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:77:15
    at Generator.next (<anonymous>)
    at /erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:4:12)
    at supergraphCompose (/erxes-gateway/dist/gateway/src/apollo-router/supergraph-compose.js:76:12)
    at /erxes-gateway/dist/gateway/src/apollo-router/index.js:78:44
    at Generator.next (<anonymous>)
    at /erxes-gateway/dist/gateway/src/apollo-router/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/erxes-gateway/dist/gateway/src/apollo-router/index.js:4:12)
    at startRouter (/erxes-gateway/dist/gateway/src/apollo-router/index.js:77:39)
    at /erxes-gateway/dist/gateway/src/index.js:79:39
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by McLeanAdam** [comment]
It would appear the permission on `apollo-router-config` are incorrect. Running the below command seems to correct the issue, can this be correct in the build scripts.

```chmod 777 -R apollo-router-config```
