### ISSUE TITLE
Ubuntu Installation doesn't work

### ISSUE THREAD

**Issue by stevennt** [erxes/erxes#4675]
**Describe the bug**
Ubuntu Installation doesn't work. https://docs.erxes.io/docs/developer/ubuntu/

**To Reproduce**
Follow this guide exactly: https://docs.erxes.io/docs/developer/ubuntu/

**Expected behavior**
Tried with both Node 14 and 16 as suggested in the guide. Doesn't work.

**Screenshots**
![image](https://github.com/erxes/erxes/assets/32351181/5210c464-0fbe-408c-902d-06cd92e23629)

**Context (please include the related information if applicable):**
 - OS: Debian latest
 - Browser version: Chrome
 - erxes version: dev branch of the repo
 - installation type: docker

**Additional context**
`pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/thanhson/.pm2/pm2.log last 15 lines:
PM2        | 2023-10-06T17:09:25: PM2 log: App [logs-api:2] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-06T17:09:25: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-06T17:09:25: PM2 log: App [gateway:4] starting in -fork mode-
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] starting in -fork mode-
PM2        | 2023-10-06T17:09:25: PM2 log: App [gateway:4] online
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] online
PM2        | 2023-10-06T17:09:25: PM2 log: App [gateway:4] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-06T17:09:25: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] starting in -fork mode-
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] online
PM2        | 2023-10-06T17:09:25: PM2 error: Cancelling versioning data parsing
PM2        | 2023-10-06T17:09:25: PM2 error: Cancelling versioning data parsing
PM2        | 2023-10-06T17:09:25: PM2 log: App [dashboard:3] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-06T17:09:25: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"

/home/thanhson/.pm2/logs/coreui-out.log last 15 lines:
/home/thanhson/.pm2/logs/core-out.log last 15 lines:
/home/thanhson/.pm2/logs/logs-api-out.log last 15 lines:
/home/thanhson/.pm2/logs/dashboard-out.log last 15 lines:
/home/thanhson/.pm2/logs/gateway-out.log last 15 lines:
/home/thanhson/.pm2/logs/core-error.log last 15 lines:
1|core     | /usr/share/yarn/bin/yarn:2
1|core     | argv0=$(echo "$0" | sed -e 's,\\,/,g')
1|core     |         ^^^^
1|core     | 
1|core     | SyntaxError: missing ) after argument list
1|core     |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
1|core     |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
1|core     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
1|core     |     at Module.load (internal/modules/cjs/loader.js:979:32)
1|core     |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
1|core     |     at Object.<anonymous> (/home/thanhson/.nvm/versions/node/v16.20.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|core     |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
1|core     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
1|core     |     at Module.load (internal/modules/cjs/loader.js:979:32)
1|core     |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)

/home/thanhson/.pm2/logs/coreui-error.log last 15 lines:
0|coreui   | /usr/share/yarn/bin/yarn:2
0|coreui   | argv0=$(echo "$0" | sed -e 's,\\,/,g')
0|coreui   |         ^^^^
0|coreui   | 
0|coreui   | SyntaxError: missing ) after argument list
0|coreui   |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
0|coreui   |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
0|coreui   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
0|coreui   |     at Module.load (internal/modules/cjs/loader.js:979:32)
0|coreui   |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
0|coreui   |     at Object.<anonymous> (/home/thanhson/.nvm/versions/node/v16.20.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|coreui   |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
0|coreui   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
0|coreui   |     at Module.load (internal/modules/cjs/loader.js:979:32)
0|coreui   |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)

/home/thanhson/.pm2/logs/logs-api-error.log last 15 lines:
2|logs-api | /usr/share/yarn/bin/yarn:2
2|logs-api | argv0=$(echo "$0" | sed -e 's,\\,/,g')
2|logs-api |         ^^^^
2|logs-api | 
2|logs-api | SyntaxError: missing ) after argument list
2|logs-api |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
2|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
2|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
2|logs-api |     at Module.load (internal/modules/cjs/loader.js:979:32)
2|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
2|logs-api |     at Object.<anonymous> (/home/thanhson/.nvm/versions/node/v16.20.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|logs-api |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
2|logs-api |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
2|logs-api |     at Module.load (internal/modules/cjs/loader.js:979:32)
2|logs-api |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)

/home/thanhson/.pm2/logs/gateway-error.log last 15 lines:
4|gateway  | /usr/share/yarn/bin/yarn:2
4|gateway  | argv0=$(echo "$0" | sed -e 's,\\,/,g')
4|gateway  |         ^^^^
4|gateway  | 
4|gateway  | SyntaxError: missing ) after argument list
4|gateway  |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
4|gateway  |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
4|gateway  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
4|gateway  |     at Module.load (internal/modules/cjs/loader.js:979:32)
4|gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
4|gateway  |     at Object.<anonymous> (/home/thanhson/.nvm/versions/node/v16.20.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
4|gateway  |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
4|gateway  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
4|gateway  |     at Module.load (internal/modules/cjs/loader.js:979:32)
4|gateway  |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)

/home/thanhson/.pm2/logs/dashboard-error.log last 15 lines:
3|dashboar | /usr/share/yarn/bin/yarn:2
3|dashboar | argv0=$(echo "$0" | sed -e 's,\\,/,g')
3|dashboar |         ^^^^
3|dashboar | 
3|dashboar | SyntaxError: missing ) after argument list
3|dashboar |     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
3|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1078:27)
3|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
3|dashboar |     at Module.load (internal/modules/cjs/loader.js:979:32)
3|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
3|dashboar |     at Object.<anonymous> (/home/thanhson/.nvm/versions/node/v16.20.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
3|dashboar |     at Module._compile (internal/modules/cjs/loader.js:1114:14)
3|dashboar |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
3|dashboar |     at Module.load (internal/modules/cjs/loader.js:979:32)
3|dashboar |     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
`

**Comment by Omsoni06** [comment]
I am using windows, but facing same issue  :-(
