### ISSUE TITLE
Installation of an erxes project using Docker on Ubuntu didn't work

### ISSUE THREAD

**Issue by Niba-nazar** [erxes/erxes#4689]
Hi,

With the help of the documentation found at https://docs.erxes.io/docs/developer/ubuntu/, I tried installing Erxes. But it's turning out like this.

![image](https://github.com/erxes/erxes/assets/114569256/31e4ed18-a532-4eb3-989c-7cadab38d411)

The log I got is listed below:

```
root@591455682a93:/erxes/cli# pm2 logs -f
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-10-18T04:34:24: PM2 log: App [dashboard:3] starting in -fork mode-
PM2        | 2023-10-18T04:34:24: PM2 log: App [dashboard:3] online
PM2        | 2023-10-18T04:34:24: PM2 log: App [coreui:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-18T04:34:24: PM2 log: App [core:1] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-18T04:34:24: PM2 log: App [gateway:4] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: App [gateway:4] starting in -fork mode-
PM2        | 2023-10-18T04:34:24: PM2 log: App [logs-api:2] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-18T04:34:24: PM2 log: App [gateway:4] online
PM2        | 2023-10-18T04:34:24: PM2 log: App [dashboard:3] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-10-18T04:34:24: PM2 log: App [gateway:4] exited with code [1] via signal [SIGINT]
PM2        | 2023-10-18T04:34:24: PM2 log: Script /usr/bin/yarn had too many unstable restarts (16). Stopped. "errored"

/root/.pm2/logs/coreui-out.log last 15 lines:
/root/.pm2/logs/core-out.log last 15 lines:
/root/.pm2/logs/logs-api-out.log last 15 lines:
/root/.pm2/logs/dashboard-out.log last 15 lines:
/root/.pm2/logs/gateway-out.log last 15 lines:
/root/.pm2/logs/erxes-error.log last 15 lines:
/root/.pm2/logs/erxes-out.log last 15 lines:
5|erxes    |   dev [options]             Run erxes in dev mode using pm2
5|erxes    |   dev-only                  Run only given service
5|erxes    |   dev-stop                  Stop pm2 services
5|erxes    |   start [options]           Run erxes
5|erxes    |   deploy-dbs                Delpoy dbs using docker
5|erxes    |   dump-db [options]         Dump database
5|erxes    |   up [options]              Run erxes using docker
5|erxes    |   update [options]
5|erxes    |   restart
5|erxes    |   remove-service
5|erxes    |   syncui
5|erxes    |   installer-update-configs
5|erxes    |   deploy-mongobi
5|erxes    |   upgrade                   Download the latest changes of erxes
5|erxes    |   help [command]            display help for command

/root/.pm2/logs/coreui-error.log last 15 lines:
0|coreui   | /usr/share/yarn/bin/yarn:2
0|coreui   | argv0=$(echo "$0" | sed -e 's,\\,/,g')
0|coreui   |         ^^^^
0|coreui   | 
0|coreui   | SyntaxError: missing ) after argument list
0|coreui   |     at Object.compileFunction (node:vm:360:18)
0|coreui   |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
0|coreui   |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
0|coreui   |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|coreui   |     at Module.load (node:internal/modules/cjs/loader:1076:32)
0|coreui   |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
0|coreui   |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|coreui   |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
0|coreui   |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|coreui   |     at Module.load (node:internal/modules/cjs/loader:1076:32)

/root/.pm2/logs/core-error.log last 15 lines:
1|core     | /usr/share/yarn/bin/yarn:2
1|core     | argv0=$(echo "$0" | sed -e 's,\\,/,g')
1|core     |         ^^^^
1|core     | 
1|core     | SyntaxError: missing ) after argument list
1|core     |     at Object.compileFunction (node:vm:360:18)
1|core     |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
1|core     |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
1|core     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
1|core     |     at Module.load (node:internal/modules/cjs/loader:1076:32)
1|core     |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
1|core     |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|core     |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
1|core     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
1|core     |     at Module.load (node:internal/modules/cjs/loader:1076:32)

/root/.pm2/logs/logs-api-error.log last 15 lines:
2|logs-api | /usr/share/yarn/bin/yarn:2
2|logs-api | argv0=$(echo "$0" | sed -e 's,\\,/,g')
2|logs-api |         ^^^^
2|logs-api | 
2|logs-api | SyntaxError: missing ) after argument list
2|logs-api |     at Object.compileFunction (node:vm:360:18)
2|logs-api |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
2|logs-api |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
2|logs-api |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2|logs-api |     at Module.load (node:internal/modules/cjs/loader:1076:32)
2|logs-api |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2|logs-api |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|logs-api |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
2|logs-api |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2|logs-api |     at Module.load (node:internal/modules/cjs/loader:1076:32)

/root/.pm2/logs/dashboard-error.log last 15 lines:
3|dashboar | /usr/share/yarn/bin/yarn:2
3|dashboar | argv0=$(echo "$0" | sed -e 's,\\,/,g')
3|dashboar |         ^^^^
3|dashboar | 
3|dashboar | SyntaxError: missing ) after argument list
3|dashboar |     at Object.compileFunction (node:vm:360:18)
3|dashboar |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
3|dashboar |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
3|dashboar |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
3|dashboar |     at Module.load (node:internal/modules/cjs/loader:1076:32)
3|dashboar |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
3|dashboar |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
3|dashboar |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
3|dashboar |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
3|dashboar |     at Module.load (node:internal/modules/cjs/loader:1076:32)

/root/.pm2/logs/gateway-error.log last 15 lines:
4|gateway  | /usr/share/yarn/bin/yarn:2
4|gateway  | argv0=$(echo "$0" | sed -e 's,\\,/,g')
4|gateway  |         ^^^^
4|gateway  | 
4|gateway  | SyntaxError: missing ) after argument list
4|gateway  |     at Object.compileFunction (node:vm:360:18)
4|gateway  |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
4|gateway  |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
4|gateway  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
4|gateway  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
4|gateway  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
4|gateway  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
4|gateway  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
4|gateway  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
4|gateway  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
```

**Comment by vinyll** [comment]
Duplicate of #4675 ?
