### ISSUE TITLE
Installing locally does not work, ./bin/erxes.js dev --deps fails

### ISSUE THREAD

**Issue by polooner** [erxes/erxes#4867]
**Is your enhancement request related to a problem? Please describe.**

The installation guide is a bit confusing and seems incomplete. We are told to create a dock folder with a new docker-compose.yaml file, but the same file already exists in the docker. I am not sure if I made mistakes and where, but I cannot get the project to run locally.

I followed the installation guide:
https://docs.erxes.io/quickstart/groups/mac

At #7, it says to ''run the following command'' but does not display any. I assumed it wants docker compose up, and ran that.

Running ./bin/erxes.js dev --deps throws this error:
```
Error: Command failed: cd /Users/polo/erxes/packages/dashboard && yarn install
/bin/sh: line 0: cd: /Users/polo/erxes/packages/dashboard: No such file or directory
```

So I just created a packages/dashboard folder and the following happens, pm2 errors all processes:

```
╰─➤  ./bin/erxes.js dev --deps                                                                        1 ↵

Generated ui coreui .env file ....
Installing dependencies in logs .........
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.50s.

warning package.json: No license field

yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.49s.


Generated ui plugins.js file ....
Installing dependencies in core-ui .........
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.52s.



                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/Users/polo/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications coreui, core, logs-ui, logs-api, dashboard, gateway not running, starting...
[PM2] App [coreui] launched (1 instances)
[PM2] App [core] launched (1 instances)
[PM2] App [logs-ui] launched (1 instances)
[PM2] App [logs-api] launched (1 instances)
[PM2] App [dashboard] launched (1 instances)
[PM2] App [gateway] launched (1 instances)
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1  │ core         │ default     │ N/A     │ fork    │ 94003    │ 0s     │ 0    │ online    │ 5%       │ 45.8mb   │ polo     │ disabled │
│ 0  │ coreui       │ default     │ N/A     │ fork    │ 93991    │ 0s     │ 0    │ online    │ 6%       │ 46.0mb   │ polo     │ disabled │
│ 4  │ dashboard    │ default     │ N/A     │ fork    │ 94039    │ 0s     │ 0    │ online    │ 0%       │ 26.0mb   │ polo     │ disabled │
│ 5  │ gateway      │ default     │ N/A     │ fork    │ 94051    │ 0s     │ 0    │ online    │ 0%       │ 4.0mb    │ polo     │ disabled │
│ 3  │ logs-api     │ default     │ N/A     │ fork    │ 94027    │ 0s     │ 0    │ online    │ 0%       │ 28.6mb   │ polo     │ disabled │
│ 2  │ logs-ui      │ default     │ N/A     │ fork    │ 94015    │ 0s     │ 0    │ online    │ 0%       │ 30.1mb   │ polo     │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘


(base) ╭─polo@Polos-MBP ~/erxes/cli  ‹dev› 
╰─➤  pm2 list
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ core               │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 0  │ coreui             │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 4  │ dashboard          │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 5  │ gateway            │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 3  │ logs-api           │ fork     │ 15   │ errored   │ 0%       │ 0b       │
│ 2  │ logs-ui            │ fork     │ 15   │ errored   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
(base) ╭─polo@Polos-MBP ~/erxes/cli  ‹dev› 
╰─➤  pm2 restart all
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [all](ids: [ 0, 1, 2, 3, 4, 5 ])
[PM2] [coreui](0) ✓
[PM2] [core](1) ✓
[PM2] [logs-ui](2) ✓
[PM2] [logs-api](3) ✓
[PM2] [dashboard](4) ✓
[PM2] [gateway](5) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 1  │ core               │ fork     │ 16   │ stopped   │ 0%       │ 0b       │
│ 0  │ coreui             │ fork     │ 16   │ stopped   │ 0%       │ 0b       │
│ 4  │ dashboard          │ fork     │ 15   │ stopped   │ 0%       │ 0b       │
│ 5  │ gateway            │ fork     │ 15   │ stopped   │ 0%       │ 0b       │
│ 3  │ logs-api           │ fork     │ 16   │ stopped   │ 0%       │ 0b       │
│ 2  │ logs-ui            │ fork     │ 16   │ stopped   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
(base) ╭─polo@Polos-MBP ~/erxes/cli  ‹dev› 
╰─➤  pm2 logs -f 
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/Users/polo/.pm2/pm2.log last 15 lines:
PM2        | 2023-12-22T12:43:55: PM2 log: App [gateway:5] online
PM2        | 2023-12-22T12:43:55: PM2 log: App [logs-ui:2] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 log: App [coreui:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 log: App [logs-api:3] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 log: App [core:1] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 log: App [dashboard:4] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 log: App [gateway:5] exited with code [1] via signal [SIGINT]
PM2        | 2023-12-22T12:43:55: PM2 log: Script /opt/homebrew/bin/yarn had too many unstable restarts (16). Stopped. "errored"
PM2        | 2023-12-22T12:43:55: PM2 error: Cancelling versioning data parsing
PM2        | 2023-12-22T12:43:55: PM2 error: Cancelling versioning data parsing

/Users/polo/.pm2/logs/coreui-out.log last 15 lines:
/Users/polo/.pm2/logs/core-out.log last 15 lines:
/Users/polo/.pm2/logs/logs-ui-out.log last 15 lines:
/Users/polo/.pm2/logs/logs-api-out.log last 15 lines:
/Users/polo/.pm2/logs/dashboard-out.log last 15 lines:
/Users/polo/.pm2/logs/gateway-out.log last 15 lines:
/Users/polo/.pm2/logs/coreui-error.log last 15 lines:
0|coreui   | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
0|coreui   | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
0|coreui   |                        ^^^^
0|coreui   | 
0|coreui   | SyntaxError: Unexpected identifier
0|coreui   |     at internalCompileFunction (node:internal/vm:73:18)
0|coreui   |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
0|coreui   |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
0|coreui   |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|coreui   |     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|coreui   |     at Module._load (node:internal/modules/cjs/loader:960:12)
0|coreui   |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|coreui   |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|coreui   |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|coreui   |     at Module.load (node:internal/modules/cjs/loader:1119:32)

/Users/polo/.pm2/logs/core-error.log last 15 lines:
1|core     | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
1|core     | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
1|core     |                        ^^^^
1|core     | 
1|core     | SyntaxError: Unexpected identifier
1|core     |     at internalCompileFunction (node:internal/vm:73:18)
1|core     |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
1|core     |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
1|core     |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
1|core     |     at Module.load (node:internal/modules/cjs/loader:1119:32)
1|core     |     at Module._load (node:internal/modules/cjs/loader:960:12)
1|core     |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
1|core     |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
1|core     |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
1|core     |     at Module.load (node:internal/modules/cjs/loader:1119:32)

/Users/polo/.pm2/logs/logs-ui-error.log last 15 lines:
2|logs-ui  | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
2|logs-ui  | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
2|logs-ui  |                        ^^^^
2|logs-ui  | 
2|logs-ui  | SyntaxError: Unexpected identifier
2|logs-ui  |     at internalCompileFunction (node:internal/vm:73:18)
2|logs-ui  |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
2|logs-ui  |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
2|logs-ui  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|logs-ui  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
2|logs-ui  |     at Module._load (node:internal/modules/cjs/loader:960:12)
2|logs-ui  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2|logs-ui  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2|logs-ui  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|logs-ui  |     at Module.load (node:internal/modules/cjs/loader:1119:32)

/Users/polo/.pm2/logs/logs-api-error.log last 15 lines:
3|logs-api | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
3|logs-api | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
3|logs-api |                        ^^^^
3|logs-api | 
3|logs-api | SyntaxError: Unexpected identifier
3|logs-api |     at internalCompileFunction (node:internal/vm:73:18)
3|logs-api |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
3|logs-api |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
3|logs-api |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
3|logs-api |     at Module.load (node:internal/modules/cjs/loader:1119:32)
3|logs-api |     at Module._load (node:internal/modules/cjs/loader:960:12)
3|logs-api |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
3|logs-api |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
3|logs-api |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
3|logs-api |     at Module.load (node:internal/modules/cjs/loader:1119:32)

/Users/polo/.pm2/logs/dashboard-error.log last 15 lines:
4|dashboar | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
4|dashboar | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
4|dashboar |                        ^^^^
4|dashboar | 
4|dashboar | SyntaxError: Unexpected identifier
4|dashboar |     at internalCompileFunction (node:internal/vm:73:18)
4|dashboar |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
4|dashboar |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
4|dashboar |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
4|dashboar |     at Module.load (node:internal/modules/cjs/loader:1119:32)
4|dashboar |     at Module._load (node:internal/modules/cjs/loader:960:12)
4|dashboar |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
4|dashboar |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
4|dashboar |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
4|dashboar |     at Module.load (node:internal/modules/cjs/loader:1119:32)

/Users/polo/.pm2/logs/gateway-error.log last 15 lines:
5|gateway  | /opt/homebrew/Cellar/yarn/1.22.19/bin/yarn:2
5|gateway  | PREFIX="/opt/homebrew" exec "/opt/homebrew/Cellar/yarn/1.22.19/libexec/bin/yarn.js"  "$@"
5|gateway  |                        ^^^^
5|gateway  | 
5|gateway  | SyntaxError: Unexpected identifier
5|gateway  |     at internalCompileFunction (node:internal/vm:73:18)
5|gateway  |     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
5|gateway  |     at Module._compile (node:internal/modules/cjs/loader:1220:27)
5|gateway  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
5|gateway  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
5|gateway  |     at Module._load (node:internal/modules/cjs/loader:960:12)
5|gateway  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
5|gateway  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
5|gateway  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
5|gateway  |     at Module.load (node:internal/modules/cjs/loader:1119:32)

```

**Describe the solution you'd like**

**Comment by fraschm1998** [comment]
I have the same issue.

**Comment by luis-uppeta** [comment]
I have the same issue.

`erxes/packages/dashboard: No such file or directory`

**Comment by HornBlowerCruise** [comment]
I have same issue in installing at ubuntu : 

/bin/sh: 1: cd: can't cd to /home/ubuntu/erxes/erxes/packages/dashboard
(node:44331) UnhandledPromiseRejectionWarning: Error: Command failed: cd /home/ubuntu/erxes/erxes/packages/dashboard && yarn install
/bin/sh: 1: cd: can't cd to /home/ubuntu/erxes/erxes/packages/dashboard

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Command.module.exports.devCmd (/home/ubuntu/erxes/erxes/cli/commands/dev.js:196:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:44331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by saashqdev** [comment]
me too

**Comment by karthikdeva** [comment]
After placing the dashboard package, build got succeeded but initial-setup api if failing http://localhost:4000/initial-setup?envs={%22REACT_APP_API_URL%22:%22http://localhost:4000%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:4000/graphql%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4300%22,%22REACT_APP_FILE_UPLOAD_MAX_SIZE%22:%22%22,%22REACT_APP_APM_SERVER_URL%22:%22%22,%22REACT_APP_HIDE_MESSENGER%22:%22%2 

<img width="1693" alt="image" src="https://github.com/erxes/erxes/assets/5055278/b9cc1f09-f69a-4bf9-8518-0ba340281b19">

**Comment by saashqdev** [comment]
Interesting, mine had an issue with the gateway not starting. I'm still tinkernig....

**Comment by jemysh007** [comment]
> Build got succeeded after placing the dashboard package, but initial-setup api is failing [http://localhost:4000/initial-setup?envs={%22REACT_APP_API_URL%22:%22http://localhost:4000%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:4000/graphql%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4300%22,%22REACT_APP_FILE_UPLOAD_MAX_SIZE%22:%22%22,%22REACT_APP_APM_SERVER_URL%22:%22%22,%22REACT_APP_HIDE_MESSENGER%22:%22%2](http://localhost:4000/initial-setup?envs=%7B%22REACT_APP_API_URL%22:%22http://localhost:4000%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:4000/graphql%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4300%22,%22REACT_APP_FILE_UPLOAD_MAX_SIZE%22:%22%22,%22REACT_APP_APM_SERVER_URL%22:%22%22,%22REACT_APP_HIDE_MESSENGER%22:%22%2)
> 
> <img alt="image" width="1693" src="https://private-user-images.githubusercontent.com/5055278/294850448-b9cc1f09-f69a-4bf9-8518-0ba340281b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODczNDUsIm5iZiI6MTcwNTk4NzA0NSwicGF0aCI6Ii81MDU1Mjc4LzI5NDg1MDQ0OC1iOWNjMWYwOS1mNjlhLTRiZjktODUxOC0wYmEzNDAyODFiMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDUxNzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUwNTUyYTNjNDMyYjZkZTZhYjhmZGUwNGRmMWQ0OWI0MmVjNzlmM2MxMTAyZjFjNjk5NGEyNmYyN2UzMmJmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2WVjh3OUhN3nwHDqAqTgVXR6F1Ti3EeqRKviPYLwdTw">

This same happened with me did you resolve it?

**Comment by saashqdev** [comment]
If I remember correctly, you need to check if the gateway docker container is running after the installation. I had issues with this. I haven't looked in a while but you may want to check the logs of the gatway container after installation.

**Comment by wchesley** [comment]
> me too. In a seperate temp dir I cloned erxes again then:
> 
> ```
> git checkout dashboard-from-plugin
> ```
> 
> copied the packages/dashboard dir over to my examples/erxes/packages dir and it seemed to build ok..

I too had the same issue where the dashboard directory didn't exist, on a fresh Ubuntu 22.04 installation. The above text resolved that issue and I was able to run through the initial setup. Huge thank you to @saashqdev!  

I then had issues getting the marketplace to load, #3923 helped me a bit, but doesn't provide a full resolution. I was able to piece the configs.json file together using the README in `/erxes/cli` dir. From what I understand, so long as the plugin files exist in `/erxes/packages` you can specify them in your configs.json, under the `plugins` array. Aside from just adding the plugin, I had to specify `"ui": "local"` before I saw the plugins in erxes dashboard.

**Comment by wchesley** [comment]
Absolutely! 

```json
{
	"jwt_token_secret": "token",
        "dashboard": {
	},
	"client_portal_domains": "",
	"elasticsearch": {},
	"redis": {
		"password": ""
	},
	"mongo": {
		"username": "",
		"password": ""
	},
	"rabbitmq": {
		"cookie": "",
		"user": "",
		"pass": "",
		"vhost": ""
	},
	"plugins": [
		{
			"name": "logs"
		},
		{
			"name": "webbuilder",
			"ui": "local"
		},
		{
			"name": "cards",
			"ui": "local"
		},
		{
			"name": "products",
			"ui": "local"
		},
		{
			"name": "segments",
			"ui": "local"
		}
	]
}
```

**Comment by saashqdev** [comment]
That's very cool, thanks so much...

**Comment by saashqdev** [comment]
Would anyone happen to have a db schema dump? I'm not installed atm.

**Comment by wchesley** [comment]
[erxes.tar.gz](https://github.com/erxes/erxes/files/14224201/erxes.tar.gz)

Let me know if that helps.

**Comment by saashqdev** [comment]
Ah, way cool. This really helps me out. You're a good man @wchesley

**Comment by saashqdev** [comment]
Is it possible to get and export the actual fields in the database?

**Comment by wchesley** [comment]
@soyombo-baterdene @Anu-Ujin @munkhsaikhan 

I think this issue can be closed now.

**Comment by harry873** [comment]
Build got succeeded after placing the dashboard package, but initial-setup api is failing [http://localhost:4000/initial-setup?envs={%22REACT_APP_API_URL%22:%22http://localhost:4000%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:4000/graphql%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4300%22,%22REACT_APP_FILE_UPLOAD_MAX_SIZE%22:%22%22,%22REACT_APP_APM_SERVER_URL%22:%22%22,%22REACT_APP_HIDE_MESSENGER%22:%22%2](http://localhost:4000/initial-setup?envs=%7B%22REACT_APP_API_URL%22:%22http://localhost:4000%22,%22REACT_APP_API_SUBSCRIPTION_URL%22:%22ws://localhost:4000/graphql%22,%22REACT_APP_CDN_HOST%22:%22http://localhost:3200%22,%22REACT_APP_DASHBOARD_URL%22:%22http://localhost:4300%22,%22REACT_APP_FILE_UPLOAD_MAX_SIZE%22:%22%22,%22REACT_APP_APM_SERVER_URL%22:%22%22,%22REACT_APP_HIDE_MESSENGER%22:%22%2)


If anyone has the answer of this error then please share the answer

**Comment by hemanth5544** [comment]
@harry873 any solution for the initial setup api fail issue ?still facing same issue on Ubuntu with docker installation
